### ISSUE TITLE
Can't compile with net native

### ISSUE THREAD

**Issue by iloxmn** [amerkoleci/Vortice.Mathematics#16]
#### Description (optional)

MCG0017: MCG0017:NotWinRTType Cannot marshal generic Windows Runtime types with a non Windows Runtime type as a generic type argument. Check the generic arguments of type 'System.Nullable`1<Vortice.Mathematics.Color4>'		

#### Actual Behavior

It runs in debug mode, but won't compile in release mode

**Comment by amerkoleci** [comment]
This has nothing to do from Vortice side, the issue is in your project where you use Vortice.Mathematics, seams that your using nullable Color4 and WinRT AOT cannot manage to compile it.

**Comment by iloxmn** [comment]
> This has nothing to do from Vortice side, the issue is in your project where you use Vortice.Mathematics, seams that your using nullable Color4 and WinRT AOT cannot manage to compile it.

Yes, I'm using your Vortice.Windows package and says it supports uwp. But it refers this package and it won't compile. Does downgrade this project to c# 7.3 make it work?

**Comment by amerkoleci** [comment]
Not sure, you have to give me more info, how it is used etc :)

**Comment by iloxmn** [comment]
I don't know what else information I can provide. Currently it only uses Vortice.Direct2D1, everything works fine. just won't compile when net native enabled. And the only error I get is this

**Comment by yinyue200** [comment]
old version, like 1.3.21 is work.

**Comment by deccer** [comment]
@iloxmn a reproduction repro would be nice, otherwise its a bit vague indeed
