### ISSUE TITLE
Box.Height and Box.Depth are reversed from what they should be

### ISSUE THREAD

**Issue by paulbartrum** [amerkoleci/Vortice.Mathematics#17]
I suspect the Box members are reversed from what they should be. [Height](https://github.com/amerkoleci/Vortice.Mathematics/blob/ad26b18c27d1b2a84ed56fd544a51e0479a71b47/src/Vortice.Mathematics/Box.cs#L98) should be Bottom - Top, not Top - Bottom. And [Depth](https://github.com/amerkoleci/Vortice.Mathematics/blob/ad26b18c27d1b2a84ed56fd544a51e0479a71b47/src/Vortice.Mathematics/Box.cs#L103) should be Back - Front, not Front - Back.

At least if you want to match the D3D box structure: https://docs.microsoft.com/en-us/windows/win32/api/d3d12/ns-d3d12-d3d12_box

**Comment by amerkoleci** [comment]
Yeah you're right! fixed now, new nuget package will containt FIX.

Thanks :)
