### ISSUE TITLE
Rect.ToString format seems incorrect

### ISSUE THREAD

**Issue by sdcb** [amerkoleci/Vortice.Mathematics#21]
#### Description (optional)
https://github.com/amerkoleci/Vortice.Mathematics/blob/d874d93f0185549b3b2ef64b2074817b3849f68d/src/Vortice.Mathematics/Rect.cs#L259

#### Reproduction Steps
Rect rect = new ();
Console.WriteLine(rect);

#### Expected Behavior
Rect { X = 0,  Y = 0 }, { Width = 0, Height = 0 }

#### Actual Behavior
Rect { X = 0, { Y = 0, { Width = 0, Height = 0 }

**Comment by amerkoleci** [comment]
Fixed by https://github.com/amerkoleci/Vortice.Mathematics/commit/721e0d7153e1b0ab8970170e4f9006cc54832f06
