### ISSUE TITLE
Downgrade System.Runtime.CompilerServices.Unsafe

### ISSUE THREAD

**Issue by piotrek1668** [amerkoleci/Vortice.Mathematics#22]
Vortice.Mathematics uses System.Runtime.CompilerServices.Unsafe in version 6.0.0 as a dependency. Would it be possible to downgrade the version to 4.7.0?

This will increase compatibility with other products that also use System.Runtime.CompilerServices.Unsafe as a dependency.

In the versions <= 1.9.143 the library System.Runtime.CompilerServices.Unsafe was not used at all. There the compatibility had been higher.

**Comment by amerkoleci** [comment]
Can I ask you why? I would like to keep deps as higher as possible

**Comment by piotrek1668** [comment]
We have around 70 projects referencing System.Runtime.CompilerServices.Unsafe in version 4.7.0. If we want to use Vortice.Mathematics, we would have to update all 70 projects to use version 6.0.0. The effort for us would be very high. 

I don't know how high the effort would be to convert Vortice.Mathematics.
