### ISSUE TITLE
Clarify Ray.Intersects works on clock-wise triangles if you are using Z+ is forward.

### ISSUE THREAD

**Issue by roy-t** [amerkoleci/Vortice.Mathematics#26]
Hi, long time since we spoke 😄!

Wanted to share this small nitpick with you.

The method `public readonly bool Intersects( in Vector3 v0, in Vector3 v1, in Vector3 v2, out Vector3 pointInTriangle)` on the `Ray` struct has the following disclaimer:

> This ONLY works on CW wound triangles.

But what is clock-wise depends on the unit system the user is using. As a DirectX user, I assumed `Z-` is forward. But it looks like this code uses the OpenGL convention in which `Z+` is forward. Which means that every triangle that I believe to be clockwise, is actually counter-clockwise. 

A small proof:
```
    [Fact]
    public void RayTriangleIntersectionTest()
    {
        var position = new Vector3(2.75f, 1000.0f, 1.5f);
        var direction = new Vector3(0.0f, -1.0f, 0.0f);
        var ray = new Ray(position, direction);

        // nw---ne
        //  \    |
        //   \   |
        //    \ se

        var nw = new Vector3(2, 18, 1);
        var ne = new Vector3(3, 18, 1);
        var se = new Vector3(3, 18, 2);

        var hitCW = ray.Intersects(nw, ne, se, out var pitCW);
        var hitCCW = ray.Intersects(se, ne, nw, out var pitCCW);
        True(hitCW);
        False(hitCCW);
    }
```

It would be nice to add a small clarification, so that users double check what convention they are using.

**Comment by amerkoleci** [comment]
Hi,
Latest commit https://github.com/amerkoleci/Vortice.Mathematics/commit/7a17c60476a9672de833b5e5da1f3911498a1b02 handles this, can you try with latest version and see if it works as wanted?

Thanks

**Comment by roy-t** [comment]
Hey!

I've copy pasted the new method and it works great without modification. I also like that there is a version now that just gives you the distance instead of a point!
